# Copyright 2017 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "package_typescript_30_e2e")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") 

# rules_nodejs is required to load npm dependencies with yarn_install
# http_archive(
#    name = "build_bazel_rules_nodejs",
#    urls = ["https://github.com/bazelbuild/rules_nodejs/archive/0.16.4.zip"],
#    strip_prefix = "rules_nodejs-0.16.4",
# )
local_repository(
    name = "build_bazel_rules_nodejs",
    path="../../../../rules_nodejs",
)

# install rules_nodejs transitive dependencies with rules_nodejs_dependencies
load("@build_bazel_rules_nodejs//:package.bzl", "rules_nodejs_dependencies")

rules_nodejs_dependencies()

# setup nodejs with node_repositories and install npm dependencies with yarn_install
load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories", "yarn_install")

node_repositories()

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

# install rules_typescript bazel workspace using install_rules_typescript
# function from npm which fetches the rules_typescript http_archive corresponding
# to the @bazel/typescript and @bazel/karma npm packages
load("@npm//rules_typescript:package.bzl", "install_rules_typescript")

# Using a local repository for rules_typescript since we are in the rules_typescript
# repository
local_repository(
    name = "build_bazel_rules_typescript",
    path = "../../..",
)

install_rules_typescript()

# setup typescript toolchain
load("@build_bazel_rules_typescript//:defs.bzl", "ts_setup_workspace")

ts_setup_workspace()
